### ISSUE TITLE
known variable

### ISSUE THREAD

**Issue by shruti9619** [KartikKannapur/Getting-Started-with-Firebase-in-Python#2]
I failed to understand what gdgbangalore_chat_url is and props?

**Comment by KartikKannapur** [comment]
`prop` was a properties file that I had created which contained Firebase application specific keys(such as `prop_gdgbangalore_chat_url` and `prop_firebase_url`). I could not share that with the public(since it was a private key). You can replace those variables with the keys for your application.

**Comment by shruti9619** [comment]
I understand that but I need to know which key is required. See the prop_firebase_url one I understood which url it meant but the other one I am not able to understand. Where in firebase will I get the other url from? I m new to firebase. Thanks!

**Comment by KartikKannapur** [comment]
Since this repository is about two years old & there have been a lot of changes since then to the Firebase product itself, I haven't updated the code in this repository. I would recommend using some of the newer libraries(such as https://github.com/thisbejim/Pyrebase) or going through their documentation for REST APIs(https://firebase.google.com/docs/database/rest/start)

At this point of time, that is all I would be able to help with, in regard to this codebase.

If you have another repository where you are working on something related to Firebase and Python, do let me know in case you need any help with that.

**Comment by shruti9619** [comment]
Thank you 👍  :)
